const elements = [
  {
    x: 1,
    y: 1,
    num: 1,
    sym: "H",
    name: "Hidrógeno",
    mass: "1.008",
    group: "nonmetals",
    desc: "El más abundante del universo.",
    props: { Estado: "Gas", Electronegatividad: "2.20" },
  },
  {
    x: 18,
    y: 1,
    num: 2,
    sym: "He",
    name: "Helio",
    mass: "4.0026",
    group: "nobles",
    desc: "Gas noble inerte y ligero.",
    props: { Estado: "Gas", Electronegatividad: "—" },
  },
  {
    x: 1,
    y: 2,
    num: 3,
    sym: "Li",
    name: "Litio",
    mass: "6.94",
    group: "metals",
    desc: "Metal alcalino muy reactivo.",
    props: { Estado: "Sólido", Electronegatividad: "0.98" },
  },
  {
    x: 2,
    y: 2,
    num: 4,
    sym: "Be",
    name: "Berilio",
    mass: "9.0122",
    group: "metals",
    desc: "Metal alcalinotérreo.",
    props: { Estado: "Sólido", Electronegatividad: "1.57" },
  },
  {
    x: 13,
    y: 2,
    num: 5,
    sym: "B",
    name: "Boro",
    mass: "10.81",
    group: "metalloids",
    desc: "Metaloide usado en vidrio y detergentes.",
    props: { Estado: "Sólido", Electronegatividad: "2.04" },
  },
  {
    x: 14,
    y: 2,
    num: 6,
    sym: "C",
    name: "Carbono",
    mass: "12.011",
    group: "nonmetals",
    desc: "Base de la vida orgánica.",
    props: { Estado: "Sólido", Electronegatividad: "2.55" },
  },
  {
    x: 15,
    y: 2,
    num: 7,
    sym: "N",
    name: "Nitrógeno",
    mass: "14.007",
    group: "nonmetals",
    desc: "Gas que forma el 78% del aire.",
    props: { Estado: "Gas", Electronegatividad: "3.04" },
  },
  {
    x: 16,
    y: 2,
    num: 8,
    sym: "O",
    name: "Oxígeno",
    mass: "15.999",
    group: "nonmetals",
    desc: "Esencial para la respiración.",
    props: { Estado: "Gas", Electronegatividad: "3.44" },
  },
  {
    x: 17,
    y: 2,
    num: 9,
    sym: "F",
    name: "Flúor",
    mass: "18.998",
    group: "halogenos",
    desc: "El más electronegativo.",
    props: { Estado: "Gas", Electronegatividad: "3.98" },
  },
  {
    x: 18,
    y: 2,
    num: 10,
    sym: "Ne",
    name: "Neón",
    mass: "20.180",
    group: "nobles",
    desc: "Gas noble usado en luces.",
    props: { Estado: "Gas", Electronegatividad: "—" },
  },
  {
    x: 1,
    y: 3,
    num: 11,
    sym: "Na",
    name: "Sodio",
    mass: "22.990",
    group: "metals",
    desc: "Metal alcalino, esencial en la vida.",
    props: { Estado: "Sólido", Electronegatividad: "0.93" },
  },
  {
    x: 2,
    y: 3,
    num: 12,
    sym: "Mg",
    name: "Magnesio",
    mass: "24.305",
    group: "metals",
    desc: "Metal ligero y resistente.",
    props: { Estado: "Sólido", Electronegatividad: "1.31" },
  },
  {
    x: 13,
    y: 3,
    num: 13,
    sym: "Al",
    name: "Aluminio",
    mass: "26.982",
    group: "metals",
    desc: "Metal liviano y conductor.",
    props: { Estado: "Sólido", Electronegatividad: "1.61" },
  },
  {
    x: 14,
    y: 3,
    num: 14,
    sym: "Si",
    name: "Silicio",
    mass: "28.085",
    group: "metalloids",
    desc: "Metaloide usado en electrónica.",
    props: { Estado: "Sólido", Electronegatividad: "1.90" },
  },
  {
    x: 15,
    y: 3,
    num: 15,
    sym: "P",
    name: "Fósforo",
    mass: "30.974",
    group: "nonmetals",
    desc: "Importante en ADN y energía celular.",
    props: { Estado: "Sólido", Electronegatividad: "2.19" },
  },
  {
    x: 16,
    y: 3,
    num: 16,
    sym: "S",
    name: "Azufre",
    mass: "32.06",
    group: "nonmetals",
    desc: "Elemento amarillo, presente en proteínas.",
    props: { Estado: "Sólido", Electronegatividad: "2.58" },
  },
  {
    x: 17,
    y: 3,
    num: 17,
    sym: "Cl",
    name: "Cloro",
    mass: "35.45",
    group: "halogenos",
    desc: "Gas verde amarillento desinfectante.",
    props: { Estado: "Gas", Electronegatividad: "3.16" },
  },
  {
    x: 18,
    y: 3,
    num: 18,
    sym: "Ar",
    name: "Argón",
    mass: "39.948",
    group: "nobles",
    desc: "Gas noble abundante en la atmósfera.",
    props: { Estado: "Gas", Electronegatividad: "—" },
  },
  {
    x: 1,
    y: 4,
    num: 19,
    sym: "K",
    name: "Potasio",
    mass: "39.098",
    group: "metals",
    desc: "Metal esencial en procesos biológicos.",
    props: { Estado: "Sólido", Electronegatividad: "0.82" },
  },
  {
    x: 2,
    y: 4,
    num: 20,
    sym: "Ca",
    name: "Calcio",
    mass: "40.078",
    group: "metals",
    desc: "Metal esencial para huesos y dientes.",
    props: { Estado: "Sólido", Electronegatividad: "1.00" },
  },
  {
    x: 3,
    y: 4,
    num: 21,
    sym: "Sc",
    name: "Escandio",
    mass: "44.956",
    group: "metals",
    desc: "Metal de transición usado en aleaciones.",
    props: { Estado: "Sólido", Electronegatividad: "1.36" },
  },
  {
    x: 4,
    y: 4,
    num: 22,
    sym: "Ti",
    name: "Titanio",
    mass: "47.867",
    group: "metals",
    desc: "Metal resistente y ligero.",
    props: { Estado: "Sólido", Electronegatividad: "1.54" },
  },
  {
    x: 5,
    y: 4,
    num: 23,
    sym: "V",
    name: "Vanadio",
    mass: "50.942",
    group: "metals",
    desc: "Usado en aceros especiales.",
    props: { Estado: "Sólido", Electronegatividad: "1.63" },
  },
  {
    x: 6,
    y: 4,
    num: 24,
    sym: "Cr",
    name: "Cromo",
    mass: "51.996",
    group: "metals",
    desc: "Brillante y resistente a la corrosión.",
    props: { Estado: "Sólido", Electronegatividad: "1.66" },
  },
  {
    x: 7,
    y: 4,
    num: 25,
    sym: "Mn",
    name: "Manganeso",
    mass: "54.938",
    group: "metals",
    desc: "Usado en aceros y baterías.",
    props: { Estado: "Sólido", Electronegatividad: "1.55" },
  },
  {
    x: 8,
    y: 4,
    num: 26,
    sym: "Fe",
    name: "Hierro",
    mass: "55.845",
    group: "metals",
    desc: "Metal más usado en la industria.",
    props: { Estado: "Sólido", Electronegatividad: "1.83" },
  },
  {
    x: 9,
    y: 4,
    num: 27,
    sym: "Co",
    name: "Cobalto",
    mass: "58.933",
    group: "metals",
    desc: "Usado en aleaciones y baterías.",
    props: { Estado: "Sólido", Electronegatividad: "1.88" },
  },
  {
    x: 10,
    y: 4,
    num: 28,
    sym: "Ni",
    name: "Níquel",
    mass: "58.693",
    group: "metals",
    desc: "Resistente a la corrosión.",
    props: { Estado: "Sólido", Electronegatividad: "1.91" },
  },
  {
    x: 11,
    y: 4,
    num: 29,
    sym: "Cu",
    name: "Cobre",
    mass: "63.546",
    group: "metals",
    desc: "Excelente conductor eléctrico.",
    props: { Estado: "Sólido", Electronegatividad: "1.90" },
  },
  {
    x: 12,
    y: 4,
    num: 30,
    sym: "Zn",
    name: "Zinc",
    mass: "65.38",
    group: "metals",
    desc: "Protege el hierro de la oxidación.",
    props: { Estado: "Sólido", Electronegatividad: "1.65" },
  },
  {
    x: 13,
    y: 4,
    num: 31,
    sym: "Ga",
    name: "Galio",
    mass: "69.723",
    group: "metals",
    desc: "Metal que se funde en la mano.",
    props: { Estado: "Sólido", Electronegatividad: "1.81" },
  },
  {
    x: 14,
    y: 4,
    num: 32,
    sym: "Ge",
    name: "Germanio",
    mass: "72.63",
    group: "metalloids",
    desc: "Semiconductor parecido al silicio.",
    props: { Estado: "Sólido", Electronegatividad: "2.01" },
  },
  {
    x: 15,
    y: 4,
    num: 33,
    sym: "As",
    name: "Arsénico",
    mass: "74.922",
    group: "metalloids",
    desc: "Metaloide venenoso.",
    props: { Estado: "Sólido", Electronegatividad: "2.18" },
  },
  {
    x: 16,
    y: 4,
    num: 34,
    sym: "Se",
    name: "Selenio",
    mass: "78.971",
    group: "nonmetals",
    desc: "Usado en vidrio y electrónica.",
    props: { Estado: "Sólido", Electronegatividad: "2.55" },
  },
  {
    x: 17,
    y: 4,
    num: 35,
    sym: "Br",
    name: "Bromo",
    mass: "79.904",
    group: "halogenos",
    desc: "Líquido rojo oscuro a temperatura ambiente.",
    props: { Estado: "Líquido", Electronegatividad: "2.96" },
  },
  {
    x: 18,
    y: 4,
    num: 36,
    sym: "Kr",
    name: "Kriptón",
    mass: "83.798",
    group: "nobles",
    desc: "Gas noble usado en lámparas.",
    props: { Estado: "Gas", Electronegatividad: "—" },
  },
  {
    x: 1,
    y: 5,
    num: 37,
    sym: "Rb",
    name: "Rubidio",
    mass: "85.468",
    group: "metals",
    desc: "Metal alcalino muy reactivo.",
    props: { Estado: "Sólido", Electronegatividad: "0.82" },
  },
  {
    x: 2,
    y: 5,
    num: 38,
    sym: "Sr",
    name: "Estroncio",
    mass: "87.62",
    group: "metals",
    desc: "Usado en fuegos artificiales rojos.",
    props: { Estado: "Sólido", Electronegatividad: "0.95" },
  },
  {
    x: 3,
    y: 5,
    num: 39,
    sym: "Y",
    name: "Itrio",
    mass: "88.906",
    group: "metals",
    desc: "Usado en pantallas y superconductores.",
    props: { Estado: "Sólido", Electronegatividad: "1.22" },
  },
  {
    x: 4,
    y: 5,
    num: 40,
    sym: "Zr",
    name: "Circonio",
    mass: "91.224",
    group: "metals",
    desc: "Resistente a la corrosión.",
    props: { Estado: "Sólido", Electronegatividad: "1.33" },
  },
  {
    x: 5,
    y: 5,
    num: 41,
    sym: "Nb",
    name: "Niobio",
    mass: "92.906",
    group: "metals",
    desc: "Usado en aceros especiales.",
    props: { Estado: "Sólido", Electronegatividad: "1.6" },
  },
  {
    x: 6,
    y: 5,
    num: 42,
    sym: "Mo",
    name: "Molibdeno",
    mass: "95.95",
    group: "metals",
    desc: "Aumenta la dureza del acero.",
    props: { Estado: "Sólido", Electronegatividad: "2.16" },
  },
  {
    x: 7,
    y: 5,
    num: 43,
    sym: "Tc",
    name: "Tecnecio",
    mass: "98",
    group: "metals",
    desc: "Radiactivo, usado en medicina.",
    props: { Estado: "Sólido", Electronegatividad: "1.9" },
  },
  {
    x: 8,
    y: 5,
    num: 44,
    sym: "Ru",
    name: "Rutenio",
    mass: "101.07",
    group: "metals",
    desc: "Metal raro del grupo del platino.",
    props: { Estado: "Sólido", Electronegatividad: "2.2" },
  },
  {
    x: 9,
    y: 5,
    num: 45,
    sym: "Rh",
    name: "Rodio",
    mass: "102.91",
    group: "metals",
    desc: "Muy valioso y brillante.",
    props: { Estado: "Sólido", Electronegatividad: "2.28" },
  },
  {
    x: 10,
    y: 5,
    num: 46,
    sym: "Pd",
    name: "Paladio",
    mass: "106.42",
    group: "metals",
    desc: "Usado en catalizadores.",
    props: { Estado: "Sólido", Electronegatividad: "2.2" },
  },
  {
    x: 11,
    y: 5,
    num: 47,
    sym: "Ag",
    name: "Plata",
    mass: "107.87",
    group: "metals",
    desc: "Excelente conductor eléctrico.",
    props: { Estado: "Sólido", Electronegatividad: "1.93" },
  },
  {
    x: 12,
    y: 5,
    num: 48,
    sym: "Cd",
    name: "Cadmio",
    mass: "112.41",
    group: "metals",
    desc: "Tóxico, usado en baterías antiguas.",
    props: { Estado: "Sólido", Electronegatividad: "1.69" },
  },
  {
    x: 13,
    y: 5,
    num: 49,
    sym: "In",
    name: "Indio",
    mass: "114.82",
    group: "metals",
    desc: "Usado en pantallas LCD.",
    props: { Estado: "Sólido", Electronegatividad: "1.78" },
  },
  {
    x: 14,
    y: 5,
    num: 50,
    sym: "Sn",
    name: "Estaño",
    mass: "118.71",
    group: "metals",
    desc: "Usado para proteger metales.",
    props: { Estado: "Sólido", Electronegatividad: "1.96" },
  },
  {
    x: 15,
    y: 5,
    num: 51,
    sym: "Sb",
    name: "Antimonio",
    mass: "121.76",
    group: "metalloids",
    desc: "Metaloide brillante y frágil.",
    props: { Estado: "Sólido", Electronegatividad: "2.05" },
  },
  {
    x: 16,
    y: 5,
    num: 52,
    sym: "Te",
    name: "Telurio",
    mass: "127.60",
    group: "metalloids",
    desc: "Usado en aleaciones y semiconductores.",
    props: { Estado: "Sólido", Electronegatividad: "2.1" },
  },
  {
    x: 17,
    y: 5,
    num: 53,
    sym: "I",
    name: "Yodo",
    mass: "126.90",
    group: "halogenos",
    desc: "Necesario en la tiroides.",
    props: { Estado: "Sólido", Electronegatividad: "2.66" },
  },
  {
    x: 18,
    y: 5,
    num: 54,
    sym: "Xe",
    name: "Xenón",
    mass: "131.29",
    group: "nobles",
    desc: "Gas noble usado en luces.",
    props: { Estado: "Gas", Electronegatividad: "—" },
  },
  {
    x: 1,
    y: 6,
    num: 55,
    sym: "Cs",
    name: "Cesio",
    mass: "132.91",
    group: "metals",
    desc: "Metal alcalino muy reactivo.",
    props: { Estado: "Sólido", Electronegatividad: "0.79" },
  },
  {
    x: 2,
    y: 6,
    num: 56,
    sym: "Ba",
    name: "Bario",
    mass: "137.33",
    group: "metals",
    desc: "Usado en radiografías digestivas.",
    props: { Estado: "Sólido", Electronegatividad: "0.89" },
  },
  {
    x: 3,
    y: 6,
    num: "57-71",
    sym: "", 
    name: "Lantánidos",
    mass: "", 
    group: "lantanidos",
    desc: "Serie de Lantánidos (Tierras Raras).",
    props: { Estado: "Sólido", Electronegatividad: "—" },
  },
  {
    x: 4,
    y: 6,
    num: 72,
    sym: "Hf",
    name: "Hafnio",
    mass: "178.49",
    group: "metals",
    desc: "Resistente a la corrosión.",
    props: { Estado: "Sólido", Electronegatividad: "1.3" },
  },
  {
    x: 5,
    y: 6,
    num: 73,
    sym: "Ta",
    name: "Tántalo",
    mass: "180.95",
    group: "metals",
    desc: "Usado en electrónica.",
    props: { Estado: "Sólido", Electronegatividad: "1.5" },
  },
  {
    x: 6,
    y: 6,
    num: 74,
    sym: "W",
    name: "Wolframio",
    mass: "183.84",
    group: "metals",
    desc: "El metal con mayor punto de fusión.",
    props: { Estado: "Sólido", Electronegatividad: "2.36" },
  },
  {
    x: 7,
    y: 6,
    num: 75,
    sym: "Re",
    name: "Renio",
    mass: "186.21",
    group: "metals",
    desc: "Usado en superaleaciones.",
    props: { Estado: "Sólido", Electronegatividad: "1.9" },
  },
  {
    x: 8,
    y: 6,
    num: 76,
    sym: "Os",
    name: "Osmio",
    mass: "190.23",
    group: "metals",
    desc: "El elemento más denso.",
    props: { Estado: "Sólido", Electronegatividad: "2.2" },
  },
  {
    x: 9,
    y: 6,
    num: 77,
    sym: "Ir",
    name: "Iridio",
    mass: "192.22",
    group: "metals",
    desc: "Resistente a la corrosión y denso.",
    props: { Estado: "Sólido", Electronegatividad: "2.2" },
  },
  {
    x: 10,
    y: 6,
    num: 78,
    sym: "Pt",
    name: "Platino",
    mass: "195.08",
    group: "metals",
    desc: "Metal precioso y catalizador.",
    props: { Estado: "Sólido", Electronegatividad: "2.28" },
  },
  {
    x: 11,
    y: 6,
    num: 79,
    sym: "Au",
    name: "Oro",
    mass: "196.97",
    group: "metals",
    desc: "Dúctil, maleable, buen conductor.",
    props: { Estado: "Sólido", Electronegatividad: "2.54" },
  },
  {
    x: 12,
    y: 6,
    num: 80,
    sym: "Hg",
    name: "Mercurio",
    mass: "200.59",
    group: "metals",
    desc: "Único metal líquido a temp. ambiente.",
    props: { Estado: "Líquido", Electronegatividad: "2.00" },
  },
  {
    x: 13,
    y: 6,
    num: 81,
    sym: "Tl",
    name: "Talio",
    mass: "204.38",
    group: "metals",
    desc: "Metal blando, muy tóxico.",
    props: { Estado: "Sólido", Electronegatividad: "1.62" },
  },
  {
    x: 14,
    y: 6,
    num: 82,
    sym: "Pb",
    name: "Plomo",
    mass: "207.2",
    group: "metals",
    desc: "Metal pesado, tóxico.",
    props: { Estado: "Sólido", Electronegatividad: "1.87" },
  },
  {
    x: 15,
    y: 6,
    num: 83,
    sym: "Bi",
    name: "Bismuto",
    mass: "208.98",
    group: "metals",
    desc: "El metal pesado estable menos tóxico.",
    props: { Estado: "Sólido", Electronegatividad: "2.02" },
  },
  {
    x: 16,
    y: 6,
    num: 84,
    sym: "Po",
    name: "Polonio",
    mass: "209",
    group: "metalloids",
    desc: "Radiactivo, potente fuente de calor.",
    props: { Estado: "Sólido", Electronegatividad: "2.0" },
  },
  {
    x: 17,
    y: 6,
    num: 85,
    sym: "At",
    name: "Astato",
    mass: "210",
    group: "halogenos",
    desc: "El halógeno más pesado y radiactivo.",
    props: { Estado: "Sólido", Electronegatividad: "2.2" },
  },
  {
    x: 18,
    y: 6,
    num: 86,
    sym: "Rn",
    name: "Radón",
    mass: "222",
    group: "nobles",
    desc: "Gas noble radiactivo.",
    props: { Estado: "Gas", Electronegatividad: "—" },
  },
  {
    x: 1,
    y: 7,
    num: 87,
    sym: "Fr",
    name: "Francio",
    mass: "223",
    group: "metals",
    desc: "El metal alcalino más reactivo y raro.",
    props: { Estado: "Sólido", Electronegatividad: "0.7" },
  },
  {
    x: 2,
    y: 7,
    num: 88,
    sym: "Ra",
    name: "Radio",
    mass: "226",
    group: "metals",
    desc: "Radiactivo, brilla en la oscuridad.",
    props: { Estado: "Sólido", Electronegatividad: "0.9" },
  },
  {
    x: 3,
    y: 7,
    num: "89-103",
    sym: "", 
    name: "Actínidos",
    mass: "", 
    group: "actinidos",
    desc: "Serie de Actínidos (Radiactivos).",
    props: { Estado: "Sólido", Electronegatividad: "—" },
  },
  {
    x: 4,
    y: 7,
    num: 104,
    sym: "Rf",
    name: "Rutherfordio",
    mass: "267",
    group: "metals",
    desc: "Elemento sintético y radiactivo.",
    props: { Estado: "Sólido", Electronegatividad: "—" },
  },
  {
    x: 5,
    y: 7,
    num: 105,
    sym: "Db",
    name: "Dubnio",
    mass: "268",
    group: "metals",
    desc: "Elemento sintético y radiactivo.",
    props: { Estado: "Sólido", Electronegatividad: "—" },
  },
  {
    x: 6,
    y: 7,
    num: 106,
    sym: "Sg",
    name: "Seaborgio",
    mass: "271",
    group: "metals",
    desc: "Elemento sintético y radiactivo.",
    props: { Estado: "Sólido", Electronegatividad: "—" },
  },
  {
    x: 7,
    y: 7,
    num: 107,
    sym: "Bh",
    name: "Bohrio",
    mass: "272",
    group: "metals",
    desc: "Elemento sintético y radiactivo.",
    props: { Estado: "Sólido", Electronegatividad: "—" },
  },
  {
    x: 8,
    y: 7,
    num: 108,
    sym: "Hs",
    name: "Hasio",
    mass: "270",
    group: "metals",
    desc: "Elemento sintético y radiactivo.",
    props: { Estado: "Sólido", Electronegatividad: "—" },
  },
  {
    x: 9,
    y: 7,
    num: 109,
    sym: "Mt",
    name: "Meitnerio",
    mass: "276",
    group: "metals",
    desc: "Elemento sintético y radiactivo.",
    props: { Estado: "Sólido", Electronegatividad: "—" },
  },
  {
    x: 10,
    y: 7,
    num: 110,
    sym: "Ds",
    name: "Darmstadtio",
    mass: "281",
    group: "metals",
    desc: "Elemento sintético y radiactivo.",
    props: { Estado: "Sólido", Electronegatividad: "—" },
  },
  {
    x: 11,
    y: 7,
    num: 111,
    sym: "Rg",
    name: "Roentgenio",
    mass: "280",
    group: "metals",
    desc: "Elemento sintético y radiactivo.",
    props: { Estado: "Sólido", Electronegatividad: "—" },
  },
  {
    x: 12,
    y: 7,
    num: 112,
    sym: "Cn",
    name: "Copernicio",
    mass: "285",
    group: "metals",
    desc: "Elemento sintético y radiactivo.",
    props: { Estado: "Líquido", Electronegatividad: "—" },
  },
  {
    x: 13,
    y: 7,
    num: 113,
    sym: "Nh",
    name: "Nihonio",
    mass: "286",
    group: "metals",
    desc: "Elemento sintético y radiactivo.",
    props: { Estado: "Sólido", Electronegatividad: "—" },
  },
  {
    x: 14,
    y: 7,
    num: 114,
    sym: "Fl",
    name: "Flerovio",
    mass: "289",
    group: "metals",
    desc: "Elemento sintético y radiactivo.",
    props: { Estado: "Sólido", Electronegatividad: "—" },
  },
  {
    x: 15,
    y: 7,
    num: 115,
    sym: "Mc",
    name: "Moscovio",
    mass: "290",
    group: "metals",
    desc: "Elemento sintético y radiactivo.",
    props: { Estado: "Sólido", Electronegatividad: "—" },
  },
  {
    x: 16,
    y: 7,
    num: 116,
    sym: "Lv",
    name: "Livermorio",
    mass: "293",
    group: "metals",
    desc: "Elemento sintético y radiactivo.",
    props: { Estado: "Sólido", Electronegatividad: "—" },
  },
  {
    x: 17,
    y: 7,
    num: 117,
    sym: "Ts",
    name: "Teneso",
    mass: "294",
    group: "halogenos",
    desc: "Elemento sintético y radiactivo.",
    props: { Estado: "Sólido", Electronegatividad: "—" },
  },
  {
    x: 18,
    y: 7,
    num: 118,
    sym: "Og",
    name: "Oganesón",
    mass: "294",
    group: "nobles",
    desc: "Elemento sintético y radiactivo.",
    props: { Estado: "Gas", Electronegatividad: "—" },
  },
  
  {
    x: 4,
    y: 9,
    num: 57,
    sym: "La",
    name: "Lantano",
    mass: "138.91",
    group: "lantanidos",
    desc: "Inicio de los lantánidos.",
    props: { Estado: "Sólido", Electronegatividad: "1.1" },
  },
  {
    x: 5,
    y: 9,
    num: 58,
    sym: "Ce",
    name: "Cerio",
    mass: "140.12",
    group: "lantanidos",
    desc: "Usado en catalizadores y vidrios.",
    props: { Estado: "Sólido", Electronegatividad: "1.12" },
  },
  {
    x: 6,
    y: 9,
    num: 59,
    sym: "Pr",
    name: "Praseodimio",
    mass: "140.91",
    group: "lantanidos",
    desc: "Usado en imanes y vidrios.",
    props: { Estado: "Sólido", Electronegatividad: "1.13" },
  },
  {
    x: 7,
    y: 9,
    num: 60,
    sym: "Nd",
    name: "Neodimio",
    mass: "144.24",
    group: "lantanidos",
    desc: "Usado en imanes potentes.",
    props: { Estado: "Sólido", Electronegatividad: "1.14" },
  },
  {
    x: 8,
    y: 9,
    num: 61,
    sym: "Pm",
    name: "Prometio",
    mass: "145",
    group: "lantanidos",
    desc: "Radiactivo y raro.",
    props: { Estado: "Sólido", Electronegatividad: "—" },
  },
  {
    x: 9,
    y: 9,
    num: 62,
    sym: "Sm",
    name: "Samario",
    mass: "150.36",
    group: "lantanidos",
    desc: "Usado en imanes y reactores.",
    props: { Estado: "Sólido", Electronegatividad: "1.17" },
  },
  {
    x: 10,
    y: 9,
    num: 63,
    sym: "Eu",
    name: "Europio",
    mass: "151.96",
    group: "lantanidos",
    desc: "Usado en pantallas rojas.",
    props: { Estado: "Sólido", Electronegatividad: "1.2" },
  },
  {
    x: 11,
    y: 9,
    num: 64,
    sym: "Gd",
    name: "Gadolinio",
    mass: "157.25",
    group: "lantanidos",
    desc: "Usado en MRI y reactores.",
    props: { Estado: "Sólido", Electronegatividad: "1.2" },
  },
  {
    x: 12,
    y: 9,
    num: 65,
    sym: "Tb",
    name: "Terbio",
    mass: "158.93",
    group: "lantanidos",
    desc: "Usado en pantallas verdes.",
    props: { Estado: "Sólido", Electronegatividad: "1.2" },
  },
  {
    x: 13,
    y: 9,
    num: 66,
    sym: "Dy",
    name: "Disprosio",
    mass: "162.50",
    group: "lantanidos",
    desc: "Usado en imanes y láseres.",
    props: { Estado: "Sólido", Electronegatividad: "1.22" },
  },
  {
    x: 14,
    y: 9,
    num: 67,
    sym: "Ho",
    name: "Holmio",
    mass: "164.93",
    group: "lantanidos",
    desc: "Usado en imanes y láseres.",
    props: { Estado: "Sólido", Electronegatividad: "1.23" },
  },
  {
    x: 15,
    y: 9,
    num: 68,
    sym: "Er",
    name: "Erbio",
    mass: "167.26",
    group: "lantanidos",
    desc: "Usado en fibra óptica.",
    props: { Estado: "Sólido", Electronegatividad: "1.24" },
  },
  {
    x: 16,
    y: 9,
    num: 69,
    sym: "Tm",
    name: "Tulio",
    mass: "168.93",
    group: "lantanidos",
    desc: "Raro, usado en láseres.",
    props: { Estado: "Sólido", Electronegatividad: "1.25" },
  },
  {
    x: 17,
    y: 9,
    num: 70,
    sym: "Yb",
    name: "Iterbio",
    mass: "173.05",
    group: "lantanidos",
    desc: "Usado en aleaciones.",
    props: { Estado: "Sólido", Electronegatividad: "1.1" },
  },
  {
    x: 18,
    y: 9,
    num: 71,
    sym: "Lu",
    name: "Lutecio",
    mass: "174.97",
    group: "lantanidos",
    desc: "Último de los lantánidos.",
    props: { Estado: "Sólido", Electronegatividad: "1.27" },
  },
  
  {
    x: 4,
    y: 10,
    num: 89,
    sym: "Ac",
    name: "Actinio",
    mass: "227",
    group: "actinidos",
    desc: "Inicio de los actínidos.",
    props: { Estado: "Sólido", Electronegatividad: "1.1" },
  },
  {
    x: 5,
    y: 10,
    num: 90,
    sym: "Th",
    name: "Torio",
    mass: "232.04",
    group: "actinidos",
    desc: "Usado como combustible nuclear.",
    props: { Estado: "Sólido", Electronegatividad: "1.3" },
  },
  {
    x: 6,
    y: 10,
    num: 91,
    sym: "Pa",
    name: "Protactinio",
    mass: "231.04",
    group: "actinidos",
    desc: "Raro y radiactivo.",
    props: { Estado: "Sólido", Electronegatividad: "1.5" },
  },
  {
    x: 7,
    y: 10,
    num: 92,
    sym: "U",
    name: "Uranio",
    mass: "238.03",
    group: "actinidos",
    desc: "Combustible nuclear común.",
    props: { Estado: "Sólido", Electronegatividad: "1.38" },
  },
  {
    x: 8,
    y: 10,
    num: 93,
    sym: "Np",
    name: "Neptunio",
    mass: "237",
    group: "actinidos",
    desc: "Radiactivo, sintético.",
    props: { Estado: "Sólido", Electronegatividad: "1.36" },
  },
  {
    x: 9,
    y: 10,
    num: 94,
    sym: "Pu",
    name: "Plutonio",
    mass: "244",
    group: "actinidos",
    desc: "Usado en armas y reactores.",
    props: { Estado: "Sólido", Electronegatividad: "1.28" },
  },
  {
    x: 10,
    y: 10,
    num: 95,
    sym: "Am",
    name: "Americio",
    mass: "243",
    group: "actinidos",
    desc: "Usado en detectores de humo.",
    props: { Estado: "Sólido", Electronegatividad: "1.13" },
  },
  {
    x: 11,
    y: 10,
    num: 96,
    sym: "Cm",
    name: "Curio",
    mass: "247",
    group: "actinidos",
    desc: "Radiactivo.",
    props: { Estado: "Sólido", Electronegatividad: "1.28" },
  },
  {
    x: 12,
    y: 10,
    num: 97,
    sym: "Bk",
    name: "Berkelio",
    mass: "247",
    group: "actinidos",
    desc: "Sintético y radiactivo.",
    props: { Estado: "Sólido", Electronegatividad: "1.3" },
  },
  {
    x: 13,
    y: 10,
    num: 98,
    sym: "Cf",
    name: "Californio",
    mass: "251",
    group: "actinidos",
    desc: "Emisor de neutrones.",
    props: { Estado: "Sólido", Electronegatividad: "1.3" },
  },
  {
    x: 14,
    y: 10,
    num: 99,
    sym: "Es",
    name: "Einsteinio",
    mass: "252",
    group: "actinidos",
    desc: "Nombrado por Einstein.",
    props: { Estado: "Sólido", Electronegatividad: "1.3" },
  },
  {
    x: 15,
    y: 10,
    num: 100,
    sym: "Fm",
    name: "Fermio",
    mass: "257",
    group: "actinidos",
    desc: "Sintético.",
    props: { Estado: "Sólido", Electronegatividad: "1.3" },
  },
  {
    x: 16,
    y: 10,
    num: 101,
    sym: "Md",
    name: "Mendelevio",
    mass: "258",
    group: "actinidos",
    desc: "Llamado por Mendeléyev.",
    props: { Estado: "Sólido", Electronegatividad: "1.3" },
  },
  {
    x: 17,
    y: 10,
    num: 102,
    sym: "No",
    name: "Nobelio",
    mass: "259",
    group: "actinidos",
    desc: "Radiactivo.",
    props: { Estado: "Sólido", Electronegatividad: "1.3" },
  },
  {
    x: 18,
    y: 10,
    num: 103,
    sym: "Lr",
    name: "Lawrencio",
    mass: "266",
    group: "actinidos",
    desc: "Fin de los actínidos.",
    props: { Estado: "Sólido", Electronegatividad: "1.3" },
  },
];
const periodicTable = document.getElementById("periodic-table");
const modal = document.getElementById("modal");
const elementDetails = document.getElementById("element-details");
const closeModal = document.getElementById("close-modal");
const searchInput = document.getElementById("search");
const colorForm = document.getElementById("color-form");
function renderTable(data) {
    periodicTable.innerHTML = "";
    const maxCols = 18;
    const maxRows = 7;
    for (let r = 1; r <= maxRows; r++) {
        for (let c = 1; c <= maxCols; c++) {
            const el = data.find(e => e.x === c && e.y === r && e.group !== 'lantanidos' && e.group !== 'actinidos');
            if (el) {
                const d = document.createElement("div");
                d.className = `element ${el.group}`;
                d.style.gridColumn = el.x;
                d.style.gridRow = el.y;
                if (el.num === "57-71" || el.num === "89-103") {
                     d.className = `element f-block-link ${el.group}`;
                     d.innerHTML = `<div class='number'>${el.num}</div>`;
                     d.onclick = () => showModal(el);
                } else {
                     d.innerHTML = `<div class='number'>${el.num}</div><div class='symbol'>${el.sym}</div><div class='name'>${el.name}</div><div class='mass'>${el.mass}</div>`;
                     d.onclick = () => showModal(el);
                }
                periodicTable.appendChild(d);
            } else if (
                (r >= 4 && r <= 7) && (c >= 3 && c <= 12) && 
                !(r === 6 && c === 3) && !(r === 7 && c === 3)
            ) {
                 const empty = document.createElement("div");
                 empty.className = 'element empty';
                 empty.style.gridColumn = c;
                 empty.style.gridRow = r;
                 periodicTable.appendChild(empty);
            }
        }
    }   
    data.filter(e => e.y > maxRows).forEach((el) => {
        const d = document.createElement("div");
        d.className = `element ${el.group}`;
        d.style.gridColumn = el.x;
        d.style.gridRow = el.y;
        d.innerHTML = `<div class='number'>${el.num}</div><div class='symbol'>${el.sym}</div><div class='name'>${el.name}</div><div class='mass'>${el.mass}</div>`;
        d.onclick = () => showModal(el);
        periodicTable.appendChild(d);
    });
}
function showModal(el) {
    if (el.num === "57-71" || el.num === "89-103") {
        
        elementDetails.innerHTML = `
            <h2 style="color: var(--color-${el.group});">${el.name}</h2>
            <p class="desc">Estos elementos se muestran aparte debajo de la tabla principal.</p>
        `;
    } else { 
        elementDetails.innerHTML = '';   
        const detailsHtml = `
            <div class="symbol" style="color: var(--color-${el.group});">${el.sym}</div>
            <h2>${el.name} (${el.num})</h2>
            <div class="mass">${el.mass}</div>
            <p class="desc">${el.desc}</p>
            <div class="props">
                ${Object.entries(el.props)
                    .map(([key, value]) => `<div class="prop"><b>${key}:</b> ${value}</div>`)
                    .join("")}
            </div>
        `;
        elementDetails.innerHTML = detailsHtml;
    }
    modal.style.display = "flex";   
    modal.querySelector('.modal-content').classList.toggle('placeholder', el.num === "57-71" || el.num === "89-103");
}
closeModal.onclick = () => {
    modal.style.display = "none";
};
document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && modal.style.display === 'flex') {
        modal.style.display = 'none';
    }
});
modal.addEventListener('click', (e) => {
    if (e.target === modal) {
        modal.style.display = 'none';
    }
});
searchInput.oninput = () => {
    const query = searchInput.value.toLowerCase(); 
    const filtered = elements.filter(
        (e) =>
            (e.name.toLowerCase().includes(query) || e.sym.toLowerCase().includes(query)) && 
            !(e.num === "57-71" || e.num === "89-103")
    );
    renderTable(elements); 
    document.querySelectorAll('.element').forEach(elementDiv => {
        const symbolDiv = elementDiv.querySelector('.symbol');
        const numberDiv = elementDiv.querySelector('.number');
        let isVisible = false;
        let elementData = null;
        if (symbolDiv && symbolDiv.textContent) {
            elementData = elements.find(el => el.sym === symbolDiv.textContent);
        } else if (numberDiv && (numberDiv.textContent === "57-71" || numberDiv.textContent === "89-103")) {
            elementDiv.classList.remove('faded');
            return;
        }
        if (elementData) {
            isVisible = filtered.some(el => el.sym === elementData.sym);
        }
        if (!elementDiv.classList.contains('empty') && !elementDiv.classList.contains('f-block-link')) {
             elementDiv.classList.toggle('faded', !isVisible && query.length > 0);
        }
    });
    if (query.length === 0) {
         document.querySelectorAll('.element').forEach(elementDiv => {
            elementDiv.classList.remove('faded');
        });
    }
};
colorForm.onchange = (e) => {
    const colorName = e.target.name;
    const colorValue = e.target.value;
    document.documentElement.style.setProperty(`--color-${colorName}`, colorValue);
    renderTable(elements);
};
renderTable(elements);